version: '3'
services:

    myapp_nginx:
        build: ./API/environment/local/nginx
        container_name: 'SslMyapp'
        #<Host Port>:<Container Port> 
        ports:
        - '8081:443'
        - '8082:80'
        volumes:
        - ./API/environment/local/ssl:/etc/nginx/ssl
        - ./API/environment/local/nginx:/etc/nginx/conf.d
        - ./API/source:/var/www/html/gware
        - ./API/log:/var/log/nginx
        links:
        - webappservice
        networks:
            myapp_network:
                ipv4_address: 188.39.0.2

    webappservice:
        restart: always
        container_name: webappservice
        build: ./API/environment/local/php
        volumes:
            - ./API/source:/var/www/html/gware
        networks:
            myapp_network:
                ipv4_address: 188.39.0.3

    myapp_mysql:
        restart: always
        container_name: myapp_mysql
        build: ./API/environment/local/mysql
        environment:
            MYSQL_DATABASE: myapp_Database
            MYSQL_ROOT_PASSWORD: myapp_Password
            MYSQL_USER: myapp_User
            MYSQL_PASSWORD: Password
            TZ: Asia/Tokyo
        ports:
            - 3306:3306
        networks:
            myapp_network:
                ipv4_address: 188.39.0.4

    vue_develop:
        restart: always
        container_name: vue_develop
        build: ./VUE
        volumes:
            - "./VUE:/templates"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
        ports:
            - "8083:8080"
            - "3000:3000"
        networks:
            myapp_network:
                ipv4_address: 188.39.0.5

    vue:
        restart: always
        container_name: myapp_vue
        build: ./VUE/environment/local/server/nginx
        volumes:
            - ./VUE/environment/local/server/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./VUE/environment/local/logs/nginx/access.log:/var/log/nginx/access.log
            - ./VUE/environment/local/logs/nginx/error.log:/var/log/nginx/error.log
            - ./VUE/vue_js/dist:/var/www
            - ./VUE/environment/local/ssl:/etc/nginx/ssl
        ports:
            - "443:5050"
            - "80:5051"
        environment:
            TZ: "Asia/Tokyo"
        networks:
            myapp_network:
                ipv4_address: 188.39.0.6

    myapp_phpmyadmin:
        restart: always
        image: phpmyadmin/phpmyadmin
        container_name: myapp_phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=myapp_mysql
            - PMA_USER=myapp_User
            - PMA_PASSWORD=Password
        links:
            - myapp_mysql
        ports:
            - 7070:80

        networks:
            myapp_network:
                ipv4_address: 188.39.0.7

networks:
    myapp_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 188.39.0.0/24