<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaskInfoSeeder extends Seeder
{
    public function run()
    {
        DB::table('task_infos')->insert([
            ['taskname' => 'タスク名1','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明1','userid' => 1,'username' => 'ユーザー名1','fromuserid' => 2,'fromusername' => '依頼者名1','groupname' => 'グループ名1','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名2','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明2','userid' => 2,'username' => 'ユーザー名2','fromuserid' => 3,'fromusername' => '依頼者名2','groupname' => 'グループ名2','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名3','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明3','userid' => 3,'username' => 'ユーザー名3','fromuserid' => 4,'fromusername' => '依頼者名3','groupname' => 'グループ名3','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名4','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明4','userid' => 4,'username' => 'ユーザー名4','fromuserid' => 5,'fromusername' => '依頼者名4','groupname' => 'グループ名4','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名5','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明5','userid' => 5,'username' => 'ユーザー名5','fromuserid' => 6,'fromusername' => '依頼者名5','groupname' => 'グループ名5','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名6','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明6','userid' => 6,'username' => 'ユーザー名6','fromuserid' => 7,'fromusername' => '依頼者名6','groupname' => 'グループ名6','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名7','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明7','userid' => 7,'username' => 'ユーザー名7','fromuserid' => 8,'fromusername' => '依頼者名7','groupname' => 'グループ名7','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名8','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明8','userid' => 8,'username' => 'ユーザー名8','fromuserid' => 9,'fromusername' => '依頼者名8','groupname' => 'グループ名8','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名9','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明9','userid' => 9,'username' => 'ユーザー名9','fromuserid' => 10,'fromusername' => '依頼者名9','groupname' => 'グループ名9','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名10','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明10','userid' => 10,'username' => 'ユーザー名10','fromuserid' => 11,'fromusername' => '依頼者名10','groupname' => 'グループ名10','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名11','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明11','userid' => 11,'username' => 'ユーザー名11','fromuserid' => 12,'fromusername' => '依頼者名11','groupname' => 'グループ名11','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名12','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明12','userid' => 12,'username' => 'ユーザー名12','fromuserid' => 13,'fromusername' => '依頼者名12','groupname' => 'グループ名12','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名13','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明13','userid' => 13,'username' => 'ユーザー名13','fromuserid' => 14,'fromusername' => '依頼者名13','groupname' => 'グループ名13','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名14','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明14','userid' => 14,'username' => 'ユーザー名14','fromuserid' => 15,'fromusername' => '依頼者名14','groupname' => 'グループ名14','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名15','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明15','userid' => 15,'username' => 'ユーザー名15','fromuserid' => 16,'fromusername' => '依頼者名15','groupname' => 'グループ名15','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名16','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明16','userid' => 16,'username' => 'ユーザー名16','fromuserid' => 17,'fromusername' => '依頼者名16','groupname' => 'グループ名16','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名17','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明17','userid' => 17,'username' => 'ユーザー名17','fromuserid' => 18,'fromusername' => '依頼者名17','groupname' => 'グループ名17','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名18','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明18','userid' => 18,'username' => 'ユーザー名18','fromuserid' => 19,'fromusername' => '依頼者名18','groupname' => 'グループ名18','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名19','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明19','userid' => 19,'username' => 'ユーザー名19','fromuserid' => 20,'fromusername' => '依頼者名19','groupname' => 'グループ名19','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名20','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明20','userid' => 20,'username' => 'ユーザー名20','fromuserid' => 21,'fromusername' => '依頼者名20','groupname' => 'グループ名20','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名21','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明21','userid' => 21,'username' => 'ユーザー名21','fromuserid' => 22,'fromusername' => '依頼者名21','groupname' => 'グループ名21','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名22','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明22','userid' => 22,'username' => 'ユーザー名22','fromuserid' => 23,'fromusername' => '依頼者名22','groupname' => 'グループ名22','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名23','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明23','userid' => 23,'username' => 'ユーザー名23','fromuserid' => 24,'fromusername' => '依頼者名23','groupname' => 'グループ名23','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名24','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明24','userid' => 24,'username' => 'ユーザー名24','fromuserid' => 25,'fromusername' => '依頼者名24','groupname' => 'グループ名24','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名25','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明25','userid' => 25,'username' => 'ユーザー名25','fromuserid' => 26,'fromusername' => '依頼者名25','groupname' => 'グループ名25','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名26','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明26','userid' => 26,'username' => 'ユーザー名26','fromuserid' => 27,'fromusername' => '依頼者名26','groupname' => 'グループ名26','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名27','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明27','userid' => 27,'username' => 'ユーザー名27','fromuserid' => 28,'fromusername' => '依頼者名27','groupname' => 'グループ名27','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名28','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明28','userid' => 28,'username' => 'ユーザー名28','fromuserid' => 29,'fromusername' => '依頼者名28','groupname' => 'グループ名28','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名29','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明29','userid' => 29,'username' => 'ユーザー名29','fromuserid' => 30,'fromusername' => '依頼者名29','groupname' => 'グループ名29','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名30','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明30','userid' => 30,'username' => 'ユーザー名30','fromuserid' => 31,'fromusername' => '依頼者名30','groupname' => 'グループ名30','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名31','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明31','userid' => 31,'username' => 'ユーザー名31','fromuserid' => 32,'fromusername' => '依頼者名31','groupname' => 'グループ名31','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名32','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明32','userid' => 32,'username' => 'ユーザー名32','fromuserid' => 33,'fromusername' => '依頼者名32','groupname' => 'グループ名32','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名33','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明33','userid' => 33,'username' => 'ユーザー名33','fromuserid' => 34,'fromusername' => '依頼者名33','groupname' => 'グループ名33','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名34','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明34','userid' => 34,'username' => 'ユーザー名34','fromuserid' => 35,'fromusername' => '依頼者名34','groupname' => 'グループ名34','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名35','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明35','userid' => 35,'username' => 'ユーザー名35','fromuserid' => 36,'fromusername' => '依頼者名35','groupname' => 'グループ名35','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名36','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明36','userid' => 36,'username' => 'ユーザー名36','fromuserid' => 37,'fromusername' => '依頼者名36','groupname' => 'グループ名36','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名37','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明37','userid' => 37,'username' => 'ユーザー名37','fromuserid' => 38,'fromusername' => '依頼者名37','groupname' => 'グループ名37','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名38','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明38','userid' => 38,'username' => 'ユーザー名38','fromuserid' => 39,'fromusername' => '依頼者名38','groupname' => 'グループ名38','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名39','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明39','userid' => 39,'username' => 'ユーザー名39','fromuserid' => 40,'fromusername' => '依頼者名39','groupname' => 'グループ名39','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名40','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明40','userid' => 40,'username' => 'ユーザー名40','fromuserid' => 41,'fromusername' => '依頼者名40','groupname' => 'グループ名40','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名41','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明41','userid' => 41,'username' => 'ユーザー名41','fromuserid' => 42,'fromusername' => '依頼者名41','groupname' => 'グループ名41','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名42','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明42','userid' => 42,'username' => 'ユーザー名42','fromuserid' => 43,'fromusername' => '依頼者名42','groupname' => 'グループ名42','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名43','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明43','userid' => 43,'username' => 'ユーザー名43','fromuserid' => 44,'fromusername' => '依頼者名43','groupname' => 'グループ名43','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名44','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明44','userid' => 44,'username' => 'ユーザー名44','fromuserid' => 45,'fromusername' => '依頼者名44','groupname' => 'グループ名44','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名45','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明45','userid' => 45,'username' => 'ユーザー名45','fromuserid' => 46,'fromusername' => '依頼者名45','groupname' => 'グループ名45','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1],
            ['taskname' => 'タスク名46','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明46','userid' => 46,'username' => 'ユーザー名46','fromuserid' => 47,'fromusername' => '依頼者名46','groupname' => 'グループ名46','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 2],
            ['taskname' => 'タスク名47','taskdescription' => 'タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明タスク説明47','userid' => 47,'username' => 'ユーザー名47','fromuserid' => 48,'fromusername' => '依頼者名47','groupname' => 'グループ名47','deadline' => '2020-05-06','status' => '未','startdate' => '2020-02-06','companyid' => 1]
        ]);
    }
}
